# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    profile_images_directory: '%kernel.project_dir%/public/uploads/profile_images'
    groq_api_key: '%env(GROQ_API_KEY)%'
    groq_model: '%env(GROQ_MODEL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Security\LoginSuccessHandler:
        public: true
        autowire: true
        autoconfigure: true

    app.login_success_handler:
        class: App\Security\LoginSuccessHandler
        public: true
        autowire: true
        autoconfigure: true

    App\Service\GroqModerationService:
        arguments:
            $groqApiKey: '%groq_api_key%'
            $groqModel: '%groq_model%'